#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int adjMatriks[11][11];
int rem[11];

void intro()
{
	int i, j;
	// inisialisasi array kosong
	for(i=1;i<=10;i++){
		for(j=1;j<=10;j++){
			adjMatriks[i][j] = 0;
		}
		rem[i] = 99;
	}
	// maju cari biru
	setMotorSpeed(leftMotor,50);
  setMotorSpeed(rightMotor,50);
  while(true)
  {
  	if(getColorName(colorSensor) == colorBlue)
  	{
  		break;
  	}
	}
  while(true)
  {
  	if(getColorName(colorSensor) == colorBlack)
  	{
  		break;
  	}
	}
}

void FindGreen()
{
	while(true)
  {
  	 // sensor sees light:
    if (getColorName(colorSensor) == colorBlack){
    	motor[leftMotor]  = 55;
    	motor[rightMotor] = -15;
  	}
    else{
    	if(getColorName(colorSensor) == colorWhite){
      // counter-steer right:
      	motor[leftMotor]  = -15;
     		motor[rightMotor] = 55;
			}
			else if((getColorName(colorSensor) == colorGreen)||(getColorName(colorSensor) == colorYellow)||(getColorName(colorSensor) == colorRed)){
    		motor[leftMotor] = 0;
    		motor[rightMotor] = 0;
    		break;
    	}
    }
  }
}

void pulang()
{
	while(true)
  {
  	 // sensor sees light:
    if(getColorName(colorSensor) == colorWhite)
    {
      // counter-steer right:
      motor[leftMotor]  = -15;
      motor[rightMotor] = 55;

    }
    else if ((getColorName(colorSensor) == colorGreen)||(getColorName(colorSensor) == colorYellow)||(getColorName(colorSensor) == colorWhite)){
    	motor[leftMotor] = 0;
    	motor[rightMotor] = 0;
    	break;
    }
    // sensor sees dark:
    else
    {
      // counter-steer left:
      motor[leftMotor]  = 55;
      motor[rightMotor] = -15;
    }
  }
}

void putar(int *adakiri, int *adakanan, int *adatengah){
  int kiri, kanan, tengah;
	kiri = 0;
  tengah = 0;
  kanan = 0;

  int jumlahcabang = 0;
  // asumsi semua 90 derajat
	backward(0.3);
	int g1 = getGyroDegrees(gyroSensor);
	while (getGyroDegrees(gyroSensor) < (g1 + 90)){
		setMotorSpeed(leftMotor,20);
		setMotorSpeed(rightMotor,-20);
	}
	g1 = getGyroDegrees(gyroSensor);
	int g2 = g1;
	while(g2 > (g1-360)){
		// tambahin range pencarian
		g2 = getGyroDegrees(gyroSensor);
		if((getGyroDegrees(gyroSensor) < (g1 - 40))&&(getGyroDegrees(gyroSensor) > (g1 - 90))){
			if(getColorName(colorSensor) == colorBlack){
				kanan = 1;
			}
		}
		if((getGyroDegrees(gyroSensor) < (g1 - 140))&&(getGyroDegrees(gyroSensor) > (g1 - 180))){
			if(getColorName(colorSensor) == colorBlack){
				tengah = 1;
			}
		}
		if((getGyroDegrees(gyroSensor) < (g1 - 200))&&(getGyroDegrees(gyroSensor) > (g1 - 280))){
			if(getColorName(colorSensor) == colorBlack){
				kiri = 1;
			}
		}
		setMotorSpeed(leftMotor,20);
		setMotorSpeed(rightMotor,50);
	}
	g1 = getGyroDegrees(gyroSensor);
	jumlahcabang = kiri + kanan + tengah;
	*adakiri = kiri;
	*adakanan = kanan;
	*adatengah = tengah;
	while (getGyroDegrees(gyroSensor) > (g1 - 90)){
		setMotorSpeed(leftMotor,-20);
		setMotorSpeed(rightMotor,20);
	}
}

void turn1(){
	// posisi sudah di backward
	int g1 = getGyroDegrees(gyroSensor);
	while (getGyroDegrees(gyroSensor) > (g1 - 90)){
		setMotorSpeed(leftMotor,-20);
		setMotorSpeed(rightMotor,20);
	}
	while (getColorName(colorSensor) != colorWhite){
		setMotorSpeed(leftMotor,50);
		setMotorSpeed(rightMotor,25);
	}
	// warna putih
	while (getColorName(colorSensor) != colorBlack){
		setMotorSpeed(leftMotor,50);
		setMotorSpeed(rightMotor,25);
	}
	while (getColorName(colorSensor) != colorWhite){
		setMotorSpeed(leftMotor,50);
		setMotorSpeed(rightMotor,25);
	}
	// set break
	setMotorSpeed(leftMotor,0);
	setMotorSpeed(rightMotor,0);
}


void turn3(){
	// posisi sudah di backward
	int g1 = getGyroDegrees(gyroSensor);
	while (getGyroDegrees(gyroSensor) < (g1 + 90)){
		setMotorSpeed(leftMotor,20);
		setMotorSpeed(rightMotor,-20);
	}
	while (getColorName(colorSensor) != colorWhite){
		setMotorSpeed(leftMotor,25);
		setMotorSpeed(rightMotor,50);
	}
	// warna putih
	while (getColorName(colorSensor) != colorBlack){
		setMotorSpeed(leftMotor,25);
		setMotorSpeed(rightMotor,50);
	}
	// set break
	setMotorSpeed(leftMotor,0);
	setMotorSpeed(rightMotor,0);
}


int destination;
int startpoint;
int found = 0;

void DFS(){
	int kiri, kanan, tengah;
	FindGreen();
	if (getColorName(colorSensor) == colorGreen){
		putar(&kiri,&kanan,&tengah);
		if (kiri && kanan && tengah){
			rem[destination] = 3;
		}
		// kunjungi semua cabang
		DFS();
	}
	else if (getColorName(colorSensor) == colorRed){
		// putar balik
		int temp;
		temp = destination;
		destination = startpoint;
		startpoint = temp;
		rem[destination]--;
		FindGreen();
	}
	else if (getColorName(colorSensor) == colorYellow){
		found = 1;
		// panggil pulang
	}
}

int tipu[15];

void introtipu(){
	int i;
	for(i=1;i<15;i++){
		tipu[i] = 99;
	}
	intro();
}

void putar180(){
	int g1 = getGyroDegrees(gyroSensor);
	while (getGyroDegrees(gyroSensor) > (g1 - 180)){
		setMotorSpeed(leftMotor,-50);
		setMotorSpeed(rightMotor,50);
	}
}

void pulangtipu(){
	putar180();
	int i = destination - 1;
	while(true){
		while(tipu[i] <= 0){
			i--;
		}
		// i adalah destination
		startpoint = destination;
		destination = i;
		FindGreen();
		if (getColorName(colorSensor) != colorBlue){
			if (tipu[i] == 1){
				turn1();
			}
			else if (tipu[i] == 2){
				turn1();
				// buat turn2()
			}
			else if (tipu[i] == 3){
				turn3();
			}
		}
		else{
			break;
		}
	}
}

void DFStipu(){
	// jika hijau
	FindGreen();
	if (getColorName(colorSensor) == colorGreen){
		int kiri, kanan, tengah, banyakcabang, temp, temp2, temp3;
		putar(&kiri, &kanan, &tengah);
		//dapat angka banyaknya cabang
		banyakcabang = kiri + kanan + tengah;
		tipu[destination] = banyakcabang;
		// cari tempat kosong, assign sebagai tempat tujuan
		temp = startpoint;
		temp2 = destination;
		startpoint = destination;
		while(tipu[destination] != 99){
			destination++;
		}
		// destination adalah nomor terkecil yang kosong
		// isi sesuai banyaknya cabang dengan -1
		int i;
		for(i=destination; i< destination+banyakcabang; i++){
			tipu[i] = -1;
		}
		turn1();
		temp3 = startpoint;
		for(i=1;i<=banyakcabang;i++){
			// belok kiri
			if (found == 0){
				startpoint = temp3;
				DFStipu();
				destination = destination + 1;
			}
			else{
				break;
			}
		}
		if (found==1){
			pulangtipu();
		}
		else{
			startpoint = temp2;
			destination = temp;
			FindGreen();
			backward(0.3);
			turn1();
		}
	}
	// jika merah
	else 	if (getColorName(colorSensor) == colorRed){
		// putar 180 derajat
		tipu[destination] = 0;
		putar180();
		int temp;
		temp = startpoint;
		startpoint = destination;
		destination = temp;
		// tuker dest sama startpoint, tipu[destination] = tipu[destination] - 1
		tipu[destination] = tipu[destination] - 1;
		FindGreen();
		turn1();
		temp = startpoint;
		startpoint = destination;
		destination = temp;
	}
	// jika kuning
	else if (getColorName(colorSensor) == colorYellow){
		found = 1;
	}
}

task main()
{
	displayTextLine(1,"DFS");
	introtipu();
	startpoint = 0;
	destination = 1;
	DFStipu();
/*
	intro();
	destination = 1;
	startpoint = 0;

	FindGreen();
	putar();
	turn1();
	FindGreen();
	putar();
	turn3();
	FindGreen();
	putar();
	turn3();
	FindGreen();
/*
  sleep(2000);
  int p3 = getGyroDegrees(gyroSensor);
  int p2, adakiri, adatengah, adakanan;
  adakiri = 0;
  adatengah = 0;
  adakanan = 0;

  while(true)
  	// mode ketemu hijau
  {
  	p2 = getGyroDegrees(gyroSensor);
  	if ((p2) == (p3 + 360))
 		{
  		break;
  	}
  	else if (p2 < (p3+20))
  	{
  		  	 	if (getColorName(colorSensor) == colorBlack){
  		  	 		adatengah = 1;
  		  	 		motor[leftMotor]  = 0;
  		  	 		motor[rightMotor] = -50;
  		  	 	}
      else if (getColorName(colorSensor) == colorGreen)
      {
      	      motor[leftMotor]  = 20;
      motor[rightMotor] = 20;


  		  }
  		  else
  		  {
  		      	      motor[leftMotor]  = 40;
      motor[rightMotor] = 20;
  			}
  	}
  	else if (((p2-p3) % 360) == 90)
  	{
  		if (getColorName(colorSensor) == colorBlack){      // counter-steer right:

      motor[leftMotor]  = 0;
      motor[rightMotor] = -50;
  		adakanan = 1;}
		}
  	else if (((p2-p3) % 360) == 270)
  	{
  		if (getColorName(colorSensor) == colorBlack){
  		      // counter-steer right:

      motor[leftMotor]  = 0;
      motor[rightMotor] = -50;
  		adakiri = 1;}
		}
    else if(getColorName(colorSensor) == colorBlack)
    {
      // counter-steer right:

      motor[leftMotor]  = 0;
      motor[rightMotor] = -50;

    }
    else if (getColorName(colorSensor) == colorGreen)
    {
      motor[leftMotor]  = 20;
      motor[rightMotor] = 20;
  	}
    // sensor sees dark:
    else
    {
    	// pake mundur dikit dulu
         motor[leftMotor]  = -20;
      motor[rightMotor] = -20;
      sleep(10);
      // counter-steer left:
      motor[leftMotor]  = 0;
      motor[rightMotor] = -50;
    }
	}
	// back
	backward(1);
	while(getColorName(colorSensor) == colorGreen)
	{
		setMotorSpeed(leftMotor,-50);
		setMotorSpeed(rightMotor,-50);
	}
			setMotorSpeed(leftMotor,0);
		setMotorSpeed(rightMotor,0);
		// goto all cabang
		// pulang
		pulang();*/
while(true)
	{
		setMotorSpeed(leftMotor,0);
		setMotorSpeed(rightMotor,0);
		setMotorSpeed(armMotor,50);
		sleep(1000);
		setMotorSpeed(armMotor,-50);
		sleep(1000);
	}
}
